services:
    app:
        build:
            context: .
            target: dev
        environment:
            - DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
            - APP_HOST=${APP_HOST}
            - APP_PORT=${APP_PORT}
            - APP_AUTH_SECRET=${APP_AUTH_SECRET}
            - NODE_ENV=development
        ports:
            - ${APP_PORT}:3000
        volumes:
            - /app/node_modules
            - ./:/app
        depends_on:
            - postgres
    postgres:
        image: postgres:16.2-alpine
        container_name: quasar-postgres
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - 5430:${POSTGRES_PORT}
        volumes:
            - quasar-data:/var/lib/postgresql/data

volumes:
    quasar-data:
